baseURL = "https://kaitlynbarriere.com/"
languageCode = "en-us"
title = "Kaitlyn Barriere"
theme = "hugo-theme-dimension"

# [menu]
#   [[menu.main]]
#     name              = "Home"
#     identifier        = "home"
#     url               = "/"
#     pre               = "<i class='fa fa-home'></i>"
#     weight            = 1
#   [[menu.main]]
#     name              = "About"
#     identifier        = "about"
#     url               = "/about/"
#     pre               = "<i class='far fa-id-card'></i>"
#     weight            = 2
#   [[menu.main]]
#     name              = "Posts"
#     identifier        = "posts"
#     url               = "/posts/"
#     pre               = "<i class='far fa-newspaper'></i>"
#     weight            = 3
#   [[menu.main]]
#     name              = "Categories"
#     identifier        = "categories"
#     url               = "/categories/"
#     pre               = "<i class='fas fa-sitemap'></i>"
#     weight            = 5
#   [[menu.main]]
#     name              = "Contact"
#     identifier        = "contact"
#     url               = "/contact/"
#     pre               = "<i class='far fa-envelope'></i>"
#     weight            = 6